name: setulink_app
description: A role-based Flutter app for Citizens and Craftizens with Firebase Auth, Localization, and Maps.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.2
  firebase_messaging: ^15.1.2
  easy_localization: ^3.0.5
  provider: ^6.1.2
  google_maps_flutter: ^2.7.0
  shared_preferences: ^2.3.2
  crypto: ^3.0.3
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  location: ^5.0.3
  flutter_local_notifications: ^17.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
