name: setulink_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+16

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_analytics: ^11.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.2.4
  provider: ^6.0.0
  google_maps_flutter: 2.14.0
  location: ^5.0.3
  image_picker: ^1.2.0
  google_mlkit_text_recognition: ^0.15.0
  razorpay_flutter: ^1.3.7
  cloud_functions: ^5.0.0
  shared_preferences: ^2.0.15
  flutter_sound: ^9.2.13
  permission_handler: ^12.0.1
  audioplayers: ^6.0.0
  crypto: ^3.0.3
  geoflutterfire2: ^2.3.15
  cupertino_icons: ^1.0.2
  web: ^1.0.0
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  cloud_firestore: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/translations/

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # optional
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hex_code" # Optional, pick a color from your logo background
    theme_color: "#hex_code"
