name: setulink_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+16

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  firebase_analytics: ^10.10.0
  firebase_messaging: ^14.9.0
  flutter_local_notifications: ^17.1.2
  provider: ^6.0.0
  google_maps_flutter: ^2.1.1
  location: ^5.0.0
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.11.0
  razorpay_flutter: ^1.3.7
  cloud_functions: ^4.7.0
  shared_preferences: ^2.0.15
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  crypto: ^3.0.3
  geoflutterfire2: ^2.3.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/translations/
